language: node_js

node_js:
    - "6.1"

before_install:
    - npm install -g codeclimate-test-reporter
    - npm install -g codacy-coverage

env:
    - COVERAGE=false
    - COVERAGE=true

notifications:
  email:
    on_success: never
    on_failure: change

script:
    - './test.sh'
